stockInfopage/config/urls.py
from django.contrib import admin
from django.urls import path, include
from stockInfopage import views as daily_price
from stockInfopage import views as company
# from stockInfopage import views as home
from stockInfopage import views as dashboard
# from stockInfopage import views as lists
from stockInfopage import views as detail

#edit
from stockInfopage import views as search
urlpatterns = [
    path('admin/', admin.site.urls),
    path('company/', company.company),
    path('daily_price/', daily_price.daily_price),
    path('daily_price/<str:code>', detail.detail),#edit daily_price에서 티커명 클릭 시 세부 페이지로 이동
    path('',include('stockInfopage.urls')), # 페이징 시 URL이 해당 경로를 따라가도록 설정. stockInfopage의 urls.py 내용을 불러온다.
    path('dashboard/', dashboard.dashboard),
    path('dashboard/<str:code>', detail.detail),
    path('search/', search.search),

    #edit
    #path('lists/',lists.lists),
    #path('lists/<str:code>',detail.detail),
]

stockInfopage/stockInfopage/urls.py
from django.urls import path

from . import views

app_name = 'stockInfopage'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('company/', views.company, name='company'),
    path('daily_price/', views.daily_price, name='daily_price'),
    path('detail/', views.daily_price, name='detail'),#edit
    path('dashboard/', views.dashboard, name='dashboard'),
    path('search/', views.search, name='search'),
]

stockInfopage/stockInfopage/models.py
from django.db import models

from jsonfield import JSONField


# Create your models here.

class Company(models.Model):
    code = models.CharField(max_length=20, primary_key= True)
    company = models.CharField(max_length=40)
    last_update = models.DateField()

    def __str__(self):
        return self.company

class Daily(models.Model):
    code = models.CharField(max_length=128,primary_key=True)
    company = models.CharField(max_length=40)
    date = models.DateField()
    open = models.BigIntegerField()
    high = models.BigIntegerField()
    low = models.BigIntegerField()
    close = models.BigIntegerField()
    diff = models.BigIntegerField()
    volume = models.BigIntegerField()
    
    def __str__(self):
        return self.code

class Detaildaily(models.Model):
    code = models.CharField(max_length=128)
    company = models.CharField(max_length=40)
    date = models.DateField(primary_key=True)
    open = models.BigIntegerField()
    high = models.BigIntegerField()
    low = models.BigIntegerField()
    close = models.BigIntegerField()
    diff = models.BigIntegerField()
    volume = models.BigIntegerField()

    def __str__(self):
        return self.code

stockInfopage/stockInfopage/views.py
from unicodedata import category
from django.core import paginator
from django.core.paginator import Paginator
from django.db.models.expressions import OuterRef
from django.shortcuts import get_object_or_404, render
from .models import Company, Detaildaily
from .models import Daily
from django.db.models import Q

#crawling
from urllib.request import urlopen
from urllib.parse import quote_plus
import urllib.request
from bs4 import BeautifulSoup
import requests
import json
from django.conf import settings
import urllib.request as req

from bs4 import BeautifulSoup

from datetime import datetime, timedelta
import datetime
from dateutil.relativedelta import relativedelta
from django.utils.dateformat import DateFormat


def company(request):
    comp = Company.objects.all()
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw','') # 검색어
    #조회
    company_list = comp.order_by('code')
    if kw:
        company_list = company_list.filter(
            Q(code__icontains=kw) |
            Q(company__icontains=kw)
        ).distinct()

    #페이징처리
    paginator = Paginator(company_list, 20)
    page_obj = paginator.get_page(page)
    context = {'comp':page_obj, 'page':page, 'kw' : kw}
    return render(request, 'stockInfoPage/company.html', context)



    


def daily_price(request):
    info = Daily.objects.all()
    page = request.GET.get('page', '1')  # 페이지
    kw2 = request.GET.get('kw2', '')  # 검색어
    #조회
    daily_price= info.order_by('code')
    if kw2:
        daily_price = daily_price.filter(
            Q(code__icontains=kw2) |  # 제목검색
            Q(company__icontains=kw2)    # 내용검색
        ).distinct()

    paginator = Paginator(daily_price, 20)
    page_obj = paginator.get_page(page)
    context = {'info':page_obj, 'page':page, 'kw2':kw2}
    return render(request, 'stockInfopage/daily_price.html',context)

def home(request):
    #네이버 경제 메인 페이지 크롤링
    url = f'https://news.naver.com/main/main.nhn?mode=LSD&mid=shm&sid1=101'
    #네이버 글로벌 경제 페이지 크롤링
    finance_news_url = f'https://news.naver.com/main/list.nhn?mode=LS2D&mid=shm&sid1=101&sid2=262'

    headers = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"}
    response = requests.get(url,headers=headers)
    soup = BeautifulSoup(response.text,'html.parser')
    #네이버 글로벌 경제 금융
    res = requests.get(finance_news_url,headers=headers)
    soup2 = BeautifulSoup(res.text,'html.parser')

    #네이버 경제 메인
    my_news = soup.select('#main_content > div > div._persist > div:nth-child(1) > div.cluster_group._cluster_content > div.cluster_body > ul > li:nth-child(1) > div.cluster_text > a')
    #my_news_link = soup.select('#main_content > div.list_body.newsflash_body > ul.type06_headline > li > dl > dt:nth-child(2) > a')
    my_news_content = soup.select('#main_content > div > div._persist > div:nth-child(1) > div.cluster_group._cluster_content > div.cluster_body > ul > li:nth-child(1) > div.cluster_text > div.cluster_text_lede')
    my_news_writing = soup.select('#main_content > div > div._persist > div:nth-child(1) > div.cluster_group._cluster_content > div.cluster_body > ul > li:nth-child(1) > div.cluster_text > div.cluster_text_info > div')
    my_news_image = soup.select('#main_content > div > div._persist > div:nth-child(1) > div.cluster_group._cluster_content > div.cluster_body > ul > li:nth-child(1) > div.cluster_thumb > div.cluster_thumb_inner > a > img')
    
    newslist = list()
    nnews = list()
    # nlink = list()

    for news in my_news:
        nnews.append(news.text.strip())

    # for link in my_news_link:
    #     nlink.append(link.get('href'))
        
    for i in range(len(nnews)):
        #newslist.append([nnews[i],nlink[i]])
        title = my_news[i].text.strip()
        link = my_news[i].get('href')
        content = my_news_content[i].text.strip()
        writing = my_news_writing[i].text.strip()
        #image = my_news_image[i].get('src').replace('nf132_90','w647')
        try: #list index out of range 방지를 위한 예외처리
            image_s = my_news_image[i].get('src')
            image = my_news_image[i].get('src').replace('nf132_90','w647')
        except:
            image_s="NO IMAGE"
            image = "NO IMAGE"

        item_obj = {
            'title': title,
            'link': link,
            'content': content,
            'writing': writing,
            'image': image,
            'image_s': image_s,
        }

        newslist.append(item_obj)
   
    data = newslist

    # 네이버 뉴스 글로벌 경제_금융
    finance_news = soup2.select('#main_content > div.list_body.newsflash_body > ul.type06_headline > li > dl > dt:nth-child(2)')
    finance_link = soup2.select('#main_content > div.list_body.newsflash_body > ul.type06_headline > li > dl > dt:nth-child(2) > a')
    finance_content = soup2.select('#main_content > div.list_body.newsflash_body > ul.type06_headline > li > dl > dd > span.lede')
    finance_writing = soup2.select('#main_content > div.list_body.newsflash_body > ul.type06_headline > li > dl > dd > span.writing')
    finance_image = soup2.select('#main_content > div.list_body.newsflash_body > ul.type06_headline > li > dl > dt.photo > a > img')
    
    financenewslist = list()
    financennews = list()
    # nlink = list()

    for fnews in finance_news:
        financennews.append(fnews.text.strip())

    # for link in my_news_link:
    #     nlink.append(link.get('href'))
        
    for n in range(len(financennews)):
        #newslist.append([nnews[i],nlink[i]])
        fnews_title = finance_news[n].text.strip()
        fnews_link = finance_link[n].get('href')
        fnews_content = finance_content[n].text.strip()
        fnews_writing = finance_writing[n].text.strip()
        fnews_image = finance_image[n].get('src').replace('type=nf106_72','type=w647')

        item_obj = {
            'ftitle': fnews_title,
            'flink': fnews_link,
            'fcontent': fnews_content,
            'fwriting': fnews_writing,
            'fimage': fnews_image,
        }

        financenewslist.append(item_obj)
    
    fnews_data = financenewslist
    # 네이버 경제 금융 마지막.

    ####top종목
    urls = 'https://finance.naver.com/'
    headers = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"}
    res = requests.get(urls,headers=headers)
    #res = req.urlopen(urls).read().decode('cp949')
    #soups = BeautifulSoup(res,'html.parser')
    soups = BeautifulSoup(res.text,'html.parser')

    top = soups.select("#container > div.aside > div.group_aside > div.aside_area.aside_popular > table > tbody > tr > th")

    toplist = list()
    top2 = list()

    for tops in top:
        toplist.append(tops.text.strip())

    for i in range(len(toplist)):
        comp = top[i].text.strip()

        item_objs={
            'comp':comp,
        }
        top2.append(item_objs)
    comps = top2
    ####
    
    # 윤재락 만드는중 - home > 상한가 테스트
    url = "http://finance.naver.com/sise/"          #네이버 금융 url 주소
    res = req.urlopen(url).read().decode('cp949')   #utf-8 : 한글 깨짐, unicode_escape : 한글 깨짐, cp949로 변환해야한다.
    soup = BeautifulSoup(res, "html.parser")
 
    top101 = soup.select("#popularItemList > li > a")
    top102 = soup.select("#popularItemList > li")
    
    top10list1 = list()
    top10list2 = list()

    top101list = list()
    top102list = list()
    
    for top11 in top101:
        top10list1.append(top11.text.strip())

    for top22 in top102:
        top10list2.append(top22.text.strip())

    for i in range(len(top10list1)):
        toptext1 = top101[i].text.strip()

        item_objs={
            'toptext1':toptext1,
        }
        top101list.append(item_objs)
    data1 = top101list

    for i in range(len(top10list2)):
        toptext2 = top102[i].text.strip()

        item_objs={
            'toptext2':toptext2,
        }
        top102list.append(item_objs)
    data2 = top102list
    
    # 거래량 상위 업종 top3
    urls = 'https://finance.naver.com/main/main.nhn'
    headers = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"}
    res = requests.get(urls,headers=headers)
    soup = BeautifulSoup(res.text,'html.parser')

    sise1 = list()
    sise2 = list()

    sise_title = soup.select('#content > div.article > div.section2 > div.section_top.section_top_first > ul > li > p.item > a > strong')
    sise_diff = soup.select('#content > div.article > div.section2 > div.section_top.section_top_first > ul > li > p.item > em')

    for s1 in sise_title:
        sise1.append(s1.text.strip())
    
    for i in range(len(sise1)):
        title = sise_title[i].text.strip()
        diff = sise_diff[i].text.strip()
        
        sise_obj={
            'title':title,
            'diff': diff,
        }
        sise2.append(sise_obj)
    sise_data = sise2

    #기관 순매수
    url = 'https://finance.naver.com/sise/sise_deal_rank.nhn'         #네이버 금융 url 주소
    headers = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"}
    response = requests.get(url,headers=headers)
    soup = BeautifulSoup(response.text,'html.parser')

    organ_name = soup.find_all('a', class_ = 'company')
    organ_price = soup.find_all('td',class_ = 'number')

    organ1 = list()
    total_organ = list()

    for o in organ_name:
        organ1.append(o.text.strip())

    for o2 in range(len(organ1)):
        title = organ_name[o2].text.strip()
        price = organ_price[o2].text.strip()

        organ_obj={
            'title': title,
            'price': price,
        }
        total_organ.append(organ_obj)
    organ_data=total_organ

    context = {'data':data,'comps':comps,'data1':data1,'data2':data2,'fnews_data': fnews_data, 'sise_data':sise_data,'organ_data':organ_data,}

stockInfopage/templates/stockInfopage/company.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<!DOCTYPE html>
<html lang="ko">
<head>
  <title>코스피 기업정보</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.83.1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">
  
    <!-- Bootstrap core CSS -->
    <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- 해당 부분이 빠지면 페이징 동작 안함-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  
    <!-- Favicon -->
    <meta name="theme-color" content="#7952b3">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/home">주식정보사이트</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="/dashboard">대시보드
            <span class="visually-hidden"></span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/daily_price">일일 가격 정보</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/company">상장 기업 목록</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/search">뉴스</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container my-5">
<!-- ------------------------------- [edit] -------------------------------- -->
    <div class="row justify-content-end my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
<!-- ----------------------------------------------------------------------- -->
    <table class="table table-striped" style="font-size:15px;">
        <thead>
        <tr class="thead-dark">
            <td><B>티커명</B></td>
            <td><B>기업명</B></td>
            <td><B>업데이트 날짜</B></td>
        </tr>
        </thead>
        <tbody>
        {% for company in comp %}
        <tr>
            <td>{{company.code}}</td>
            <td>{{company.company}}</td>
            <td>{{company.last_update}}</td>
        </tr>
        {% endfor %}
        <tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if comp.has_previous %}
        <li class="page-item">
        <!-- edit -->
            <a class="page-link" data-page="{{ comp.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in comp.paginator.page_range %}
        {% if page_number >= comp.number|add:-5 and page_number <= comp.number|add:5  %}
            {% if page_number == comp.number %}
            <li class="page-item active" aria-current="page">
            <!-- edit -->
                <a class="page-link" data-page="{{ page_number }}" herf="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
            <!-- edit -->
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if comp.has_next %}
        <li class="page-item">
        <!-- edit -->
            <a class="page-link" data-page="{{ comp.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

<!-- edit -->
<form id="searchForm" method="get" action="{% url 'stockInfopage:company' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
<!-- -->
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
<script src="dashboard.js"></script>
</body>